//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace MasrafBeyanFormu.Entities {
    
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleri")]
    public class E_MasrafBeyanFormu_MasrafTipleriEntity : FormEntity<E_MasrafBeyanFormu_MasrafTipleriEntity> {
        
        private E_MasrafBeyanFormu_MasrafTipleriVREntity _VersionEntity;
        
        private RDEntityCollection<E_MasrafBeyanFormu_MasrafTipleriRDEntity, E_MasrafBeyanFormu_MasrafTipleriRDMLEntity> _RD;
        
        private RDCEntityCollection<E_MasrafBeyanFormu_MasrafTipleriRDCEntity, E_MasrafBeyanFormu_MasrafTipleriRDCMLEntity> _RDC;
        
        private GridEntityCollection<E_MasrafBeyanFormu_MasrafTipleri_DataGrid1Entity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1MLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLMLEntity> _E_MasrafBeyanFormu_MasrafTipleri_DataGrid1;
        
        public E_MasrafBeyanFormu_MasrafTipleriEntity() {
            this.VersionEntity = new E_MasrafBeyanFormu_MasrafTipleriVREntity();
            this.RD = new RDEntityCollection<E_MasrafBeyanFormu_MasrafTipleriRDEntity, E_MasrafBeyanFormu_MasrafTipleriRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_MasrafBeyanFormu_MasrafTipleriRDCEntity, E_MasrafBeyanFormu_MasrafTipleriRDCMLEntity>();
            this.E_MasrafBeyanFormu_MasrafTipleri_DataGrid1 = new GridEntityCollection<E_MasrafBeyanFormu_MasrafTipleri_DataGrid1Entity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1MLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLMLEntity>();
            this.E_MasrafBeyanFormu_MasrafTipleri_DataGrid1.MLEntityEnabled = true;
            this.E_MasrafBeyanFormu_MasrafTipleri_DataGrid1.SLEntityEnabled = false;
        }
        
        public E_MasrafBeyanFormu_MasrafTipleriVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_MasrafBeyanFormu_MasrafTipleriRDEntity, E_MasrafBeyanFormu_MasrafTipleriRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_MasrafBeyanFormu_MasrafTipleriRDCEntity, E_MasrafBeyanFormu_MasrafTipleriRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public GridEntityCollection<E_MasrafBeyanFormu_MasrafTipleri_DataGrid1Entity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1MLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLMLEntity> E_MasrafBeyanFormu_MasrafTipleri_DataGrid1 {
            get {
                return this._E_MasrafBeyanFormu_MasrafTipleri_DataGrid1;
            }
            set {
                this._E_MasrafBeyanFormu_MasrafTipleri_DataGrid1 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleri_DataGrid1")]
    public class E_MasrafBeyanFormu_MasrafTipleri_DataGrid1Entity : GridEntity<E_MasrafBeyanFormu_MasrafTipleri_DataGrid1Entity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1MLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _DGID;
        
        public E_MasrafBeyanFormu_MasrafTipleri_DataGrid1Entity() {
        }
        
        [ColumnOptionsAttribute(Name="DGID", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> DGID {
            get {
                return this._DGID;
            }
            set {
                this._DGID = value;
            }
        }
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleri_DataGrid1ML")]
    public class E_MasrafBeyanFormu_MasrafTipleri_DataGrid1MLEntity : GridMLEntity<E_MasrafBeyanFormu_MasrafTipleri_DataGrid1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _MasrafTipi;
        
        [ColumnOptionsAttribute(Name="MasrafTipi", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> MasrafTipi {
            get {
                return this._MasrafTipi;
            }
            set {
                this._MasrafTipi = value;
            }
        }
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SL")]
    public class E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLEntity : GridSLEntity<E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLEntity, E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLML")]
    public class E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLMLEntity : GridSLMLEntity<E_MasrafBeyanFormu_MasrafTipleri_DataGrid1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleriVR")]
    public class E_MasrafBeyanFormu_MasrafTipleriVREntity : VersionEntity<E_MasrafBeyanFormu_MasrafTipleriVREntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleriRDC")]
    public class E_MasrafBeyanFormu_MasrafTipleriRDCEntity : RDCEntity<E_MasrafBeyanFormu_MasrafTipleriRDCEntity, E_MasrafBeyanFormu_MasrafTipleriRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleriRDCML")]
    public class E_MasrafBeyanFormu_MasrafTipleriRDCMLEntity : RDCMLEntity<E_MasrafBeyanFormu_MasrafTipleriRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleriRD")]
    public class E_MasrafBeyanFormu_MasrafTipleriRDEntity : RDEntity<E_MasrafBeyanFormu_MasrafTipleriRDEntity, E_MasrafBeyanFormu_MasrafTipleriRDMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafTipleriRDML")]
    public class E_MasrafBeyanFormu_MasrafTipleriRDMLEntity : RDMLEntity<E_MasrafBeyanFormu_MasrafTipleriRDMLEntity> {
    }
}




