//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace MasrafBeyanFormu.Entities {
    
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormu")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuEntity : FormEntity<E_MasrafBeyanFormu_MasrafDetayFormuEntity> {
        
        private Bimser.Framework.Domain.DataField<System.DateTimeOffset> _DateTimePicker1;
        
        private Bimser.Framework.Domain.DataField<decimal> _KisiSayisi;
        
        private Bimser.Framework.Domain.DataField<decimal> _MasrafTutari;
        
        private E_MasrafBeyanFormu_MasrafDetayFormuVREntity _VersionEntity;
        
        private RDEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuRDEntity, E_MasrafBeyanFormu_MasrafDetayFormuRDMLEntity> _RD;
        
        private RDCEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuRDCEntity, E_MasrafBeyanFormu_MasrafDetayFormuRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuMLEntity> _ML;
        
        private SLEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuSLEntity, E_MasrafBeyanFormu_MasrafDetayFormuSLMLEntity> _SL;
        
        public E_MasrafBeyanFormu_MasrafDetayFormuEntity() {
            this.ML = new MLEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuMLEntity>();
            this.VersionEntity = new E_MasrafBeyanFormu_MasrafDetayFormuVREntity();
            this.RD = new RDEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuRDEntity, E_MasrafBeyanFormu_MasrafDetayFormuRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuRDCEntity, E_MasrafBeyanFormu_MasrafDetayFormuRDCMLEntity>();
            this.SL = new SLEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuSLEntity, E_MasrafBeyanFormu_MasrafDetayFormuSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="DateTimePicker1", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<System.DateTimeOffset> DateTimePicker1 {
            get {
                return this._DateTimePicker1;
            }
            set {
                this._DateTimePicker1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="KisiSayisi", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> KisiSayisi {
            get {
                return this._KisiSayisi;
            }
            set {
                this._KisiSayisi = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="MasrafTutari", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> MasrafTutari {
            get {
                return this._MasrafTutari;
            }
            set {
                this._MasrafTutari = value;
            }
        }
        
        public E_MasrafBeyanFormu_MasrafDetayFormuVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuRDEntity, E_MasrafBeyanFormu_MasrafDetayFormuRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuRDCEntity, E_MasrafBeyanFormu_MasrafDetayFormuRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_MasrafBeyanFormu_MasrafDetayFormuSLEntity, E_MasrafBeyanFormu_MasrafDetayFormuSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormuML")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuMLEntity : MLEntity<E_MasrafBeyanFormu_MasrafDetayFormuMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _Aciklama;
        
        [ColumnOptionsAttribute(Name="Aciklama", Mandatory=false, Size=250)]
        public Bimser.Framework.Domain.DataField<string> Aciklama {
            get {
                return this._Aciklama;
            }
            set {
                this._Aciklama = value;
            }
        }
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormuSL")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuSLEntity : SLEntity<E_MasrafBeyanFormu_MasrafDetayFormuSLEntity, E_MasrafBeyanFormu_MasrafDetayFormuSLMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormuSLML")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuSLMLEntity : SLMLEntity<E_MasrafBeyanFormu_MasrafDetayFormuSLMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormuVR")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuVREntity : VersionEntity<E_MasrafBeyanFormu_MasrafDetayFormuVREntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormuRDC")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuRDCEntity : RDCEntity<E_MasrafBeyanFormu_MasrafDetayFormuRDCEntity, E_MasrafBeyanFormu_MasrafDetayFormuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormuRDCML")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuRDCMLEntity : RDCMLEntity<E_MasrafBeyanFormu_MasrafDetayFormuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormuRD")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuRDEntity : RDEntity<E_MasrafBeyanFormu_MasrafDetayFormuRDEntity, E_MasrafBeyanFormu_MasrafDetayFormuRDMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_MasrafDetayFormuRDML")]
    public class E_MasrafBeyanFormu_MasrafDetayFormuRDMLEntity : RDMLEntity<E_MasrafBeyanFormu_MasrafDetayFormuRDMLEntity> {
    }
}




