//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace MasrafBeyanFormu.Entities {
    
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1")]
    public class E_MasrafBeyanFormu_Form1Entity : FormEntity<E_MasrafBeyanFormu_Form1Entity> {
        
        private Bimser.Framework.Domain.DataField<string> _UserMetadata1;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _ToplamMasraf;
        
        private E_MasrafBeyanFormu_Form1VREntity _VersionEntity;
        
        private RDEntityCollection<E_MasrafBeyanFormu_Form1RDEntity, E_MasrafBeyanFormu_Form1RDMLEntity> _RD;
        
        private RDCEntityCollection<E_MasrafBeyanFormu_Form1RDCEntity, E_MasrafBeyanFormu_Form1RDCMLEntity> _RDC;
        
        private MLEntityCollection<E_MasrafBeyanFormu_Form1MLEntity> _ML;
        
        private SLEntityCollection<E_MasrafBeyanFormu_Form1SLEntity, E_MasrafBeyanFormu_Form1SLMLEntity> _SL;
        
        private GridEntityCollection<E_MasrafBeyanFormu_Form1_MasrafDetaylariEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariMLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLMLEntity> _E_MasrafBeyanFormu_Form1_MasrafDetaylari;
        
        public E_MasrafBeyanFormu_Form1Entity() {
            this.ML = new MLEntityCollection<E_MasrafBeyanFormu_Form1MLEntity>();
            this.VersionEntity = new E_MasrafBeyanFormu_Form1VREntity();
            this.RD = new RDEntityCollection<E_MasrafBeyanFormu_Form1RDEntity, E_MasrafBeyanFormu_Form1RDMLEntity>();
            this.RDC = new RDCEntityCollection<E_MasrafBeyanFormu_Form1RDCEntity, E_MasrafBeyanFormu_Form1RDCMLEntity>();
            this.E_MasrafBeyanFormu_Form1_MasrafDetaylari = new GridEntityCollection<E_MasrafBeyanFormu_Form1_MasrafDetaylariEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariMLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLMLEntity>();
            this.E_MasrafBeyanFormu_Form1_MasrafDetaylari.MLEntityEnabled = false;
            this.E_MasrafBeyanFormu_Form1_MasrafDetaylari.SLEntityEnabled = false;
            this.SL = new SLEntityCollection<E_MasrafBeyanFormu_Form1SLEntity, E_MasrafBeyanFormu_Form1SLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="UserMetadata1", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> UserMetadata1 {
            get {
                return this._UserMetadata1;
            }
            set {
                this._UserMetadata1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="ToplamMasraf", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> ToplamMasraf {
            get {
                return this._ToplamMasraf;
            }
            set {
                this._ToplamMasraf = value;
            }
        }
        
        public E_MasrafBeyanFormu_Form1VREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_MasrafBeyanFormu_Form1RDEntity, E_MasrafBeyanFormu_Form1RDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_MasrafBeyanFormu_Form1RDCEntity, E_MasrafBeyanFormu_Form1RDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_MasrafBeyanFormu_Form1MLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_MasrafBeyanFormu_Form1SLEntity, E_MasrafBeyanFormu_Form1SLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
        
        public GridEntityCollection<E_MasrafBeyanFormu_Form1_MasrafDetaylariEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariMLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLMLEntity> E_MasrafBeyanFormu_Form1_MasrafDetaylari {
            get {
                return this._E_MasrafBeyanFormu_Form1_MasrafDetaylari;
            }
            set {
                this._E_MasrafBeyanFormu_Form1_MasrafDetaylari = value;
            }
        }
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1ML")]
    public class E_MasrafBeyanFormu_Form1MLEntity : MLEntity<E_MasrafBeyanFormu_Form1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _EkAciklama;
        
        private Bimser.Framework.Domain.DataField<string> _UserMetadata2;
        
        [ColumnOptionsAttribute(Name="EkAciklama", Mandatory=false, Size=250)]
        public Bimser.Framework.Domain.DataField<string> EkAciklama {
            get {
                return this._EkAciklama;
            }
            set {
                this._EkAciklama = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="UserMetadata2", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> UserMetadata2 {
            get {
                return this._UserMetadata2;
            }
            set {
                this._UserMetadata2 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1SL")]
    public class E_MasrafBeyanFormu_Form1SLEntity : SLEntity<E_MasrafBeyanFormu_Form1SLEntity, E_MasrafBeyanFormu_Form1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1SLML")]
    public class E_MasrafBeyanFormu_Form1SLMLEntity : SLMLEntity<E_MasrafBeyanFormu_Form1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1_MasrafDetaylari")]
    public class E_MasrafBeyanFormu_Form1_MasrafDetaylariEntity : GridEntity<E_MasrafBeyanFormu_Form1_MasrafDetaylariEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariMLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _RELATIONDOCUMENTID;
        
        public E_MasrafBeyanFormu_Form1_MasrafDetaylariEntity() {
        }
        
        [ColumnOptionsAttribute(Name="RELATIONDOCUMENTID", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> RELATIONDOCUMENTID {
            get {
                return this._RELATIONDOCUMENTID;
            }
            set {
                this._RELATIONDOCUMENTID = value;
            }
        }
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1_MasrafDetaylariML")]
    public class E_MasrafBeyanFormu_Form1_MasrafDetaylariMLEntity : GridMLEntity<E_MasrafBeyanFormu_Form1_MasrafDetaylariMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1_MasrafDetaylariSL")]
    public class E_MasrafBeyanFormu_Form1_MasrafDetaylariSLEntity : GridSLEntity<E_MasrafBeyanFormu_Form1_MasrafDetaylariSLEntity, E_MasrafBeyanFormu_Form1_MasrafDetaylariSLMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1_MasrafDetaylariSLML")]
    public class E_MasrafBeyanFormu_Form1_MasrafDetaylariSLMLEntity : GridSLMLEntity<E_MasrafBeyanFormu_Form1_MasrafDetaylariSLMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1VR")]
    public class E_MasrafBeyanFormu_Form1VREntity : VersionEntity<E_MasrafBeyanFormu_Form1VREntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1RDC")]
    public class E_MasrafBeyanFormu_Form1RDCEntity : RDCEntity<E_MasrafBeyanFormu_Form1RDCEntity, E_MasrafBeyanFormu_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1RDCML")]
    public class E_MasrafBeyanFormu_Form1RDCMLEntity : RDCMLEntity<E_MasrafBeyanFormu_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1RD")]
    public class E_MasrafBeyanFormu_Form1RDEntity : RDEntity<E_MasrafBeyanFormu_Form1RDEntity, E_MasrafBeyanFormu_Form1RDMLEntity> {
    }
    
    [TableOptions(TableName="E_MasrafBeyanFormu_Form1RDML")]
    public class E_MasrafBeyanFormu_Form1RDMLEntity : RDMLEntity<E_MasrafBeyanFormu_Form1RDMLEntity> {
    }
}




