//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace Seyahat.Entities {
    
    
    [TableOptions(TableName="E_Seyahat_Form1")]
    public class E_Seyahat_Form1Entity : FormEntity<E_Seyahat_Form1Entity> {
        
        private Bimser.Framework.Domain.DataField<decimal> _ToplamTutar;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DonusTarihi;
        
        private Bimser.Framework.Domain.DataField<string> _CepTel;
        
        private Bimser.Framework.Domain.DataField<string> _TC;
        
        private Bimser.Framework.Domain.DataField<System.DateTimeOffset> _DogumTarihii;
        
        private Bimser.Framework.Domain.DataField<System.DateTimeOffset> _GidisTarihi;
        
        private Bimser.Framework.Domain.DataField<decimal> _Bagaj;
        
        private E_Seyahat_Form1VREntity _VersionEntity;
        
        private RDEntityCollection<E_Seyahat_Form1RDEntity, E_Seyahat_Form1RDMLEntity> _RD;
        
        private RDCEntityCollection<E_Seyahat_Form1RDCEntity, E_Seyahat_Form1RDCMLEntity> _RDC;
        
        private MLEntityCollection<E_Seyahat_Form1MLEntity> _ML;
        
        private SLEntityCollection<E_Seyahat_Form1SLEntity, E_Seyahat_Form1SLMLEntity> _SL;
        
        public E_Seyahat_Form1Entity() {
            this.ML = new MLEntityCollection<E_Seyahat_Form1MLEntity>();
            this.VersionEntity = new E_Seyahat_Form1VREntity();
            this.RD = new RDEntityCollection<E_Seyahat_Form1RDEntity, E_Seyahat_Form1RDMLEntity>();
            this.RDC = new RDCEntityCollection<E_Seyahat_Form1RDCEntity, E_Seyahat_Form1RDCMLEntity>();
            this.SL = new SLEntityCollection<E_Seyahat_Form1SLEntity, E_Seyahat_Form1SLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="ToplamTutar", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> ToplamTutar {
            get {
                return this._ToplamTutar;
            }
            set {
                this._ToplamTutar = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DonusTarihi", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DonusTarihi {
            get {
                return this._DonusTarihi;
            }
            set {
                this._DonusTarihi = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="CepTel", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> CepTel {
            get {
                return this._CepTel;
            }
            set {
                this._CepTel = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="TC", Mandatory=false, Size=11)]
        public Bimser.Framework.Domain.DataField<string> TC {
            get {
                return this._TC;
            }
            set {
                this._TC = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DogumTarihii", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<System.DateTimeOffset> DogumTarihii {
            get {
                return this._DogumTarihii;
            }
            set {
                this._DogumTarihii = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="GidisTarihi", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<System.DateTimeOffset> GidisTarihi {
            get {
                return this._GidisTarihi;
            }
            set {
                this._GidisTarihi = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="Bagaj", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> Bagaj {
            get {
                return this._Bagaj;
            }
            set {
                this._Bagaj = value;
            }
        }
        
        public E_Seyahat_Form1VREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_Seyahat_Form1RDEntity, E_Seyahat_Form1RDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_Seyahat_Form1RDCEntity, E_Seyahat_Form1RDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_Seyahat_Form1MLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_Seyahat_Form1SLEntity, E_Seyahat_Form1SLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_Seyahat_Form1ML")]
    public class E_Seyahat_Form1MLEntity : MLEntity<E_Seyahat_Form1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _Eposta;
        
        private Bimser.Framework.Domain.DataField<string> _AdSoyad;
        
        [ColumnOptionsAttribute(Name="Eposta", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> Eposta {
            get {
                return this._Eposta;
            }
            set {
                this._Eposta = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="AdSoyad", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> AdSoyad {
            get {
                return this._AdSoyad;
            }
            set {
                this._AdSoyad = value;
            }
        }
    }
    
    [TableOptions(TableName="E_Seyahat_Form1SL")]
    public class E_Seyahat_Form1SLEntity : SLEntity<E_Seyahat_Form1SLEntity, E_Seyahat_Form1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_Seyahat_Form1SLML")]
    public class E_Seyahat_Form1SLMLEntity : SLMLEntity<E_Seyahat_Form1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_Seyahat_Form1VR")]
    public class E_Seyahat_Form1VREntity : VersionEntity<E_Seyahat_Form1VREntity> {
    }
    
    [TableOptions(TableName="E_Seyahat_Form1RDC")]
    public class E_Seyahat_Form1RDCEntity : RDCEntity<E_Seyahat_Form1RDCEntity, E_Seyahat_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_Seyahat_Form1RDCML")]
    public class E_Seyahat_Form1RDCMLEntity : RDCMLEntity<E_Seyahat_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_Seyahat_Form1RD")]
    public class E_Seyahat_Form1RDEntity : RDEntity<E_Seyahat_Form1RDEntity, E_Seyahat_Form1RDMLEntity> {
    }
    
    [TableOptions(TableName="E_Seyahat_Form1RDML")]
    public class E_Seyahat_Form1RDMLEntity : RDMLEntity<E_Seyahat_Form1RDMLEntity> {
    }
}




