//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace yktest.Entities {
    
    
    [TableOptions(TableName="E_yktest_Form1")]
    public class E_yktest_Form1Entity : FormEntity<E_yktest_Form1Entity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DateTimePicker1;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DateTimePicker4;
        
        private Bimser.Framework.Domain.DataField<string> _MaskInput1;
        
        private Bimser.Framework.Domain.DataField<string> _UserMetadata1;
        
        private E_yktest_Form1VREntity _VersionEntity;
        
        private RDEntityCollection<E_yktest_Form1RDEntity, E_yktest_Form1RDMLEntity> _RD;
        
        private RDCEntityCollection<E_yktest_Form1RDCEntity, E_yktest_Form1RDCMLEntity> _RDC;
        
        private MLEntityCollection<E_yktest_Form1MLEntity> _ML;
        
        private SLEntityCollection<E_yktest_Form1SLEntity, E_yktest_Form1SLMLEntity> _SL;
        
        public E_yktest_Form1Entity() {
            this.ML = new MLEntityCollection<E_yktest_Form1MLEntity>();
            this.VersionEntity = new E_yktest_Form1VREntity();
            this.RD = new RDEntityCollection<E_yktest_Form1RDEntity, E_yktest_Form1RDMLEntity>();
            this.RDC = new RDCEntityCollection<E_yktest_Form1RDCEntity, E_yktest_Form1RDCMLEntity>();
            this.SL = new SLEntityCollection<E_yktest_Form1SLEntity, E_yktest_Form1SLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="DateTimePicker1", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DateTimePicker1 {
            get {
                return this._DateTimePicker1;
            }
            set {
                this._DateTimePicker1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DateTimePicker4", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DateTimePicker4 {
            get {
                return this._DateTimePicker4;
            }
            set {
                this._DateTimePicker4 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="MaskInput1", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> MaskInput1 {
            get {
                return this._MaskInput1;
            }
            set {
                this._MaskInput1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="UserMetadata1", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> UserMetadata1 {
            get {
                return this._UserMetadata1;
            }
            set {
                this._UserMetadata1 = value;
            }
        }
        
        public E_yktest_Form1VREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_yktest_Form1RDEntity, E_yktest_Form1RDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_yktest_Form1RDCEntity, E_yktest_Form1RDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_yktest_Form1MLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_yktest_Form1SLEntity, E_yktest_Form1SLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_yktest_Form1ML")]
    public class E_yktest_Form1MLEntity : MLEntity<E_yktest_Form1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _TextArea1;
        
        private Bimser.Framework.Domain.DataField<string> _UserMetadata2;
        
        [ColumnOptionsAttribute(Name="TextArea1", Mandatory=false, Size=500)]
        public Bimser.Framework.Domain.DataField<string> TextArea1 {
            get {
                return this._TextArea1;
            }
            set {
                this._TextArea1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="UserMetadata2", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> UserMetadata2 {
            get {
                return this._UserMetadata2;
            }
            set {
                this._UserMetadata2 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_yktest_Form1SL")]
    public class E_yktest_Form1SLEntity : SLEntity<E_yktest_Form1SLEntity, E_yktest_Form1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_yktest_Form1SLML")]
    public class E_yktest_Form1SLMLEntity : SLMLEntity<E_yktest_Form1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_yktest_Form1VR")]
    public class E_yktest_Form1VREntity : VersionEntity<E_yktest_Form1VREntity> {
    }
    
    [TableOptions(TableName="E_yktest_Form1RDC")]
    public class E_yktest_Form1RDCEntity : RDCEntity<E_yktest_Form1RDCEntity, E_yktest_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_yktest_Form1RDCML")]
    public class E_yktest_Form1RDCMLEntity : RDCMLEntity<E_yktest_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_yktest_Form1RD")]
    public class E_yktest_Form1RDEntity : RDEntity<E_yktest_Form1RDEntity, E_yktest_Form1RDMLEntity> {
    }
    
    [TableOptions(TableName="E_yktest_Form1RDML")]
    public class E_yktest_Form1RDMLEntity : RDMLEntity<E_yktest_Form1RDMLEntity> {
    }
}




